plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

#===============
#=== LAYOUT ===
#===============

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/LineLength:
  Enabled: false

#===============
#=== LINT ===
#===============

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/EmptyBlock:
  Exclude:
    - "app/views/**/*"

Lint/MissingSuper:
  Exclude:
    - "app/views/**/*"
    - "app/components/**/*"

Lint/UselessConstantScoping:
  Enabled: false

#===============
#=== METRICS ===
#===============

Metrics:
  Enabled: false

#===============
#=== NAMING ===
#===============

Naming/VariableNumber:
  Exclude:
    - "app/views/**/*"
    - "app/components/**/*"

#===============
#=== RAILS ===
#===============

Rails:
  Enabled: true

Rails/Exit:
  Exclude:
    - "lib/generators/**/*"

Rails/FindEach:
  Exclude:
    - "app/views/**/*"

Rails/FilePath:
  EnforcedStyle: arguments

Rails/I18nLocaleTexts:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

#===============
#=== RAKE ===
#===============

Rake/Desc:
  Exclude:
    - "lib/tasks/annotate.rake"
    - "lib/tasks/auto_annotate_models.rake"

#===============
#=== STYLE ===
#===============

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Exclude:
    - "app/models/category.rb"
    - "app/models/component.rb"

Style/Lambda:
  EnforcedStyle: literal

Style/OpenStructUse:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

#=============
#=== RSpec ===
#=============

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
